### ISSUE TITLE
Organizion of CQ folders

### ISSUE THREAD

**Issue by mbrush** [NCATS-Tangerine/cq-notebooks#20]
The list of CQ folders is getting quite long, and will soon get longer as we create notebooks for the original CQs in the matrix [here ](https://docs.google.com/spreadsheets/d/1wbP1Ykryibcan2ZgZTOmnGp9WjcRE7nNig3akiq0PuY/edit#gid=234309826 ) (to provide a query bank for benchmarking).

Proposing here to organize into a set of higher level folders:
`cq-notebooks/Green_CQs` - will hold all the Green team CQ folders
`cq-notebooks/Orange_CQ_Set_1` - will hold Orange team CQ folders for the St Jude's demonstrator 1 
`cq-notebooks/Orange_CQ_Set_2` - will hold Orange team CQ folders for the HCST demonstrator 2
`cq-notebooks/Orange_FA_Query_Bank` - will hold the simpler benchmarking queries from the original CQ matrix

Does this sound reasonable?   Open to different names for these folders if anyone feels strongly here (e.g. a more descriptive name like `/Orange_St_Judes_CQs` instead of `Orange_CQ_Set_1` )  
  
@cmungall @mellybelly @goodb @dnahotline @jmcmurry

**Comment by mellybelly** [comment]
+1
