### ISSUE TITLE
QB1.1_GO_Annot Notebook Status

### ISSUE THREAD

**Issue by mbrush** [NCATS-Tangerine/cq-notebooks#33]
### Notebook Folder Link:  
https://github.com/NCATS-Tangerine/cq-notebooks/tree/master/Orange_QB1_Benchmark_CQs/QB1.1_GO_Annot

### Implementors: 
- @realmarcin* 

(* = notebook lead)

### Status: 
- [x] Staged (described in a readme)
- [x] Notebook started
- [x] Notebook finished (at least one)
- [x] Outcomes documented (in this ticket)

### Primary Knowledge Sources Used:

FA gene lists
Gene Ontology (GO) annotations for human genes

### APIs Used:

Biolink API

### Outcomes:

Three tables of GO annotations for FA gene sets:
- FA core genes
- FA effector genes
- FA associated genes

**Comment by realmarcin** [comment]
closed, no longer relevant
