### ISSUE TITLE
QB2.1 GO_annotation_compendium notebook status

### ISSUE THREAD

**Issue by mbrush** [NCATS-Tangerine/cq-notebooks#40]
### Notebook Folder Link:  
https://github.com/NCATS-Tangerine/cq-notebooks/tree/master/Orange_QB2_Other_CQs/Orange_GO_annotation_compendium

### Implementors: 
- @realmarcin *
- . . . 

(* = notebook lead)

### Status: 
- [x] Staged (described in a readme)
- [x] Notebook started
- [ ] Notebook finished (at least one)
- [ ] Outcomes documented (in this ticket)

### Primary Knowledge Sources Used:
- GO Annotations

### APIs Used:
- Biolink

**Comment by realmarcin** [comment]
closed, no longer relevant
